### PR TITLE
updat erules module

### PR DESCRIPTION
**Pull request by gregoryrinaldi**
update rules and exchange

### CODE REVIEW

**Comment by ebrygg** [comment]
test me

**Review by ebrygg — CHANGES_REQUESTED** [review]
Failing
Failed to execute goal on project uvms-docker-postgres-release: Could not resolve dependencies for project eu.europa.ec.fisheries.uvms.docker:uvms-docker-postgres-release:pom:3.25.0-SNAPSHOT: Could not find artifact eu.europa.ec.fisheries.uvms.exchange:liquibase:sql:4.0.15 in thirdparty (http://nexus.focus.fish/nexus/repository/thirdparty/) -

**Comment by gregoryrinaldi** [comment]
test me

**Comment by gregoryrinaldi** [comment]
test me

**Comment by ebrygg** [comment]
test me

**Comment by ebrygg** [comment]
test me

**Pull request closed without merging**
