### PR TITLE
Bumped Asset dependency to 6.7.2 and Activity dependency to 1.2.8-SWE

### PR DESCRIPTION
**Pull request by RobinMilding**

### CODE REVIEW

**Comment by RobinMilding** [comment]
test me

**Comment by RobinMilding** [comment]
test me

**Comment by RobinMilding** [comment]
test me

**Review by psjobergprivat — APPROVED** [review]
Really annoying if different tests fail on different runs. Maybe hint Peter E about which they are, but he probably knows already

**Comment by RobinMilding** [comment]
test me

**Pull request merged**
