### PR TITLE
Upped movement to 5.2.13, upped asset to 6.0.54 and upped vms web to …

### PR DESCRIPTION
**Pull request by jemster**
…0.2.0.

Also added a test for merging assets.

### CODE REVIEW

**Comment by jemster** [comment]
test me

**Review by thomasfanto — APPROVED** [review]

**Comment by jemster** [comment]
test me

**Review by peerik — APPROVED** [review]

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
test me

**Pull request merged**
