### PR TITLE
update web: 3.0.64-UVMS movement:5.2.35-UVMS stream: 0.9.7

### PR DESCRIPTION
**Pull request by ghost**
update web: 3.0.64-UVMS movement:5.2.35-UVMS stream: 0.9.7

### CODE REVIEW

**Review by jemster — CHANGES_REQUESTED** [review]
du glömde asset

**Comment by ghost** [comment]
sorry, fixed now.

**Comment by ghost** [comment]
test me

**Comment by ghost** [comment]
test me

**Comment by ghost** [comment]
test me

**Comment by ghost** [comment]
test me

**Comment by ghost** [comment]
test me

**Pull request merged**
