### PR TITLE
Upped spatial swe to 2.0.6 and told docker to start using spatial swe…

### PR DESCRIPTION
**Pull request by jemster**
…s version of liquibase

### CODE REVIEW

**Comment by jemster** [comment]
test me

**Review by peerik — APPROVED** [review]

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
test me

**Comment by jemster** [comment]
test me

**Pull request merged**
