### PR TITLE
Wildfly14 andi jee8

### PR DESCRIPTION
**Pull request by ankovi**

### CODE REVIEW

**Comment by stainii** [comment]
test me

**Review by ebrygg — CHANGES_REQUESTED** [review]
The User and Config Modules are already present in Wilfly-UnionVMS parent so you should not add them again

**Review by peerik — COMMENTED** [review]
wildfly-unionvms should not include activity/rules etc. Add them to wildfly-fluxfmc only.

**Comment by ankovi** [comment]
@peerik  Which modules should be in unionvms image?

**Comment by ebrygg** [comment]
This might help
https://focusfish.atlassian.net/wiki/spaces/UVMS/pages/18189676/Building+local+Docker+images

**Comment by ankovi** [comment]
Ok.. Done the changes you requested!

**Review by ebrygg — CHANGES_REQUESTED** [review]
No, why are you doing changes in wildly-unionvms? This will not work

**Comment by jemster** [comment]
This has not been touched in forever, closing

**Pull request closed without merging**
