### PR TITLE
Docker merge

### PR DESCRIPTION
**Pull request by AdityaPadhy**

### CODE REVIEW

**Comment by ghost** [comment]
test me

**Comment by ghost** [comment]
test me

**Review by ghost — CHANGES_REQUESTED** [review]
Most of the changes looks good, but haven't been able to run even the old test on jenkins. 

Really nice to have new releases of of spatial,exchange,rules reporting and a few others.

You need to add verification test for the new modules you have added to http://jenkins.focus.fish:8080/view/Docker/job/UVMS-Docker-dev-test/eu.europa.ec.fisheries.uvms.docker$uvms-release-test/391/testReport/eu.europa.ec.fisheries.uvms.docker.validation/ModuleAvailableSystemIT/ for activit, sale and the others. 

But would also be good with some basic rest test cases.

Expect http://jenkins.focus.fish:8080/view/Docker/job/UVMS-Docker-dev-test/391/testReport/ to have 4 failures, the frontend test are unstable but the only we have at the moment.  

If you add basic test for the new modules and the build do not add any new test failures I would be happy to merge it.

On vacation, but will be back July 24 so will have a closer look then.

Best regards James

**Comment by AdityaPadhy** [comment]
James,
Where can i find an example of verification test and where should i add it?
For the rest test case, i believe you are referring to postman tests.

Adi

**Comment by ghost** [comment]
Have integrated most of your changes and included activity and MDR in UVMS-Docker dev branch.

Have not included your pom changes, but happy to merge them as well. If you create a new pull request with only the changes to needed build on Win7.

Have also set the ActivityRestIT as Ignored for know, so would good if you got the test to pass and also add test for the other rest methods.

**Pull request closed without merging**
